In [3]:
squares = [x**2 for x in range(1,51)]
squares

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500]

In [7]:
eSquare = [x**2  for x in range(2,51) if x %2 == 0]
eSquare
PV = ['+' if x%2==0 else '-' for  x in range(1,51)]
PV

['-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+',
 '-',
 '+']

In [13]:
index = eSquare.index(196)
assert eSquare[index] == 196
index

6

In [16]:
576 in eSquare

True

In [18]:
maxNumber = max(eSquare)
minNumber = min(eSquare)
print(maxNumber)
print(minNumber)

2500
4


Enum

In [20]:
fruits = ['Apple', 'Banana', 'Orange', 'Watermelon', 'Plum', 'Grapes', 'Kiwi', 'Strawberry', 'Pear']
fruits.sort()
fruits

['Apple',
 'Banana',
 'Grapes',
 'Kiwi',
 'Orange',
 'Pear',
 'Plum',
 'Strawberry',
 'Watermelon']

In [21]:
newList = [str(i+1)+"."+fruit for i,fruit in enumerate(fruits)]
newList

['1.Apple',
 '2.Banana',
 '3.Grapes',
 '4.Kiwi',
 '5.Orange',
 '6.Pear',
 '7.Plum',
 '8.Strawberry',
 '9.Watermelon']

ZIP

In [40]:
fruits = [['Apple', 'Banana', 'Orange'], ['Watermelon', 'Plum', 'Grapes', 'Kiwi'], ['Strawberry', 'Pear', 'Mango']]
newFruits = [fruit for innerList in fruits  for fruit in innerList  ]
newFruits

['Apple',
 'Banana',
 'Orange',
 'Watermelon',
 'Plum',
 'Grapes',
 'Kiwi',
 'Strawberry',
 'Pear',
 'Mango']

In [43]:
lem = [len(v) for v in newFruits]
newFruits = list(zip(newFruits,lem))
print(newFruits)

[((('Apple', 5), 2), 2), ((('Banana', 6), 2), 2), ((('Orange', 6), 2), 2), ((('Watermelon', 10), 2), 2), ((('Plum', 4), 2), 2), ((('Grapes', 6), 2), 2), ((('Kiwi', 4), 2), 2), ((('Strawberry', 10), 2), 2), ((('Pear', 4), 2), 2), ((('Mango', 5), 2), 2)]


In [45]:
fruits=['Apple', 'Banana', 'Orange', 'Watermelon', 'Plum', 'Grapes', 'Kiwi', 'Strawberry', 'Pear', 'Mango']
prices=[47, 27, 35, 13, 28, 10, 30, 56, 15, 25]

book1 = dict(zip(fruits,prices))
book1

{'Apple': 47,
 'Banana': 27,
 'Orange': 35,
 'Watermelon': 13,
 'Plum': 28,
 'Grapes': 10,
 'Kiwi': 30,
 'Strawberry': 56,
 'Pear': 15,
 'Mango': 25}

In [46]:
text ="we are reviewing python programming topics in ise 291. it is the most popular language for data scientists. also, it is a good general purpose programming language."

In [47]:
sentences = text.split('.')
sentences

['we are reviewing python programming topics in ise 291',
 ' it is the most popular language for data scientists',
 ' also, it is a good general purpose programming language',
 '']

In [51]:
sentences1 = [s.strip().capitalize().replace('ise','ISE')+'.' for s in sentences]
sentences1

['We are reviewing python programming topics in ISE 291.',
 'It is the most popular language for data scientists.',
 'Also, it is a good general purpose programming language.',
 '.']

In [55]:
import numpy as np
arr = np.zeros(10,dtype='int32')
arr2 = np.ones((3,5),dtype='float')
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
piArr = np.full((3,3),np.pi)
piArr

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [69]:
np.random.seed(0)
arr3 = np.random.random((3,3))
arr3

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [72]:
arr1 = np.random.randint(1,10, size=10)
arr1

array([1, 4, 6, 1, 3, 4, 9, 2, 4, 4])

In [74]:
print(arr1[5:])

[4 9 2 4 4]


In [77]:
print(arr1[4:7])

[3 4 9]


In [80]:
print(arr1[::2])

[1 6 3 9 4]
