<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Name-&amp;-ID" data-toc-modified-id="Name-&amp;-ID-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Name &amp; ID</a></span></li><li><span><a href="#Problem-#-A" data-toc-modified-id="Problem-#-A-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Problem # A</a></span><ul class="toc-item"><li><span><a href="#A-1" data-toc-modified-id="A-1-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>A-1</a></span></li><li><span><a href="#A-2" data-toc-modified-id="A-2-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>A-2</a></span></li><li><span><a href="#A-3" data-toc-modified-id="A-3-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>A-3</a></span></li><li><span><a href="#A-4" data-toc-modified-id="A-4-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>A-4</a></span></li><li><span><a href="#A-5" data-toc-modified-id="A-5-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>A-5</a></span></li><li><span><a href="#A-6" data-toc-modified-id="A-6-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>A-6</a></span></li><li><span><a href="#A-7" data-toc-modified-id="A-7-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>A-7</a></span></li><li><span><a href="#A-8" data-toc-modified-id="A-8-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>A-8</a></span></li><li><span><a href="#A-9" data-toc-modified-id="A-9-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>A-9</a></span></li><li><span><a href="#A-10" data-toc-modified-id="A-10-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>A-10</a></span></li></ul></li><li><span><a href="#Problem-#-B" data-toc-modified-id="Problem-#-B-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Problem # B</a></span><ul class="toc-item"><li><span><a href="#B-1" data-toc-modified-id="B-1-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>B-1</a></span></li><li><span><a href="#B-2" data-toc-modified-id="B-2-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>B-2</a></span></li><li><span><a href="#B-3" data-toc-modified-id="B-3-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>B-3</a></span></li><li><span><a href="#B-4" data-toc-modified-id="B-4-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>B-4</a></span></li><li><span><a href="#B-5" data-toc-modified-id="B-5-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>B-5</a></span></li><li><span><a href="#B-6" data-toc-modified-id="B-6-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>B-6</a></span></li><li><span><a href="#B-7" data-toc-modified-id="B-7-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>B-7</a></span></li><li><span><a href="#B-8" data-toc-modified-id="B-8-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>B-8</a></span></li><li><span><a href="#B-9" data-toc-modified-id="B-9-3.9"><span class="toc-item-num">3.9&nbsp;&nbsp;</span>B-9</a></span></li><li><span><a href="#B-10" data-toc-modified-id="B-10-3.10"><span class="toc-item-num">3.10&nbsp;&nbsp;</span>B-10</a></span></li></ul></li></ul></div>

# Name & ID

In [ ]:
Name= 'First_Name  Last_Name'    #write your name

In [ ]:
ID= 202012345   #write your student ID

In [ ]:
# Execute this cell 
try:
    if (Name== 'First_Name  Last_Name')  | (ID== 202012345):
        raise ValueError('''
    **************************MISSING INFO*****************************
    Enter your name & student ID in the top cells (& execute the cells)
    *******************************************************************''') 
except:
    raise ValueError('''
    **************************MISSING INFO*****************************
    Enter your name & student ID in the top cells (& execute the cells)
    *******************************************************************''')
else:
    print('All set, you can proceed!')

# Problem # A

## A-1

In [ ]:
#Answer for A-1

"""
The len() function is used to get the length or number of items in an given object. Object should be sequence such as bytes, tuple, list, or range or 
object should be a  collection (such as a dictionary, set, or frozen set).
"""
# print(len(l1)) ==> 5
# print(len(l2)) ==> 10

## A-2

In [ ]:
#Answer for A-2
"""
The purpose of this function is to get the index as well as the value of that index of a iterable object or an oject that supports iterable.
For example It is useful, when you have a list over which you want to iterate, as well as keep track of index
"""

'''
print(list(enumerate(l1))) will print the list of length 5 that contains 5 tuples. Each tuple has two element. First elemnt is the index and second is the relevant item of l1.
print(dict(enumerate(l1))) will print the dictionary of length 5. index of the list are taken as the key and the relevant items are taken as the values
Let l1 = ['Apple', 'Banana', 'Orange', 'Watermelon', 'Plum']
'''
# print(list(enumerate(l1))) => [(0, 'Apple'), (1, 'Banana'), (2, 'Orange'), (3, 'Watermelon'), (4, 'Plum')]
# print(dict(enumerate(la))) => {0: 'Apple', 1: 'Banana', 2: 'Orange', 3: 'Watermelon', 4: 'Plum'}

## A-3

In [118]:
#Answer for A-3
l1 = [i if not j else -1 * i for i in range(1,10) for j in range(2)]  # first loop go for 9 times. each of the iteration it agin go inner loop and produce two outputs
print(l1)

[1, -1, 2, -2, 3, -3, 4, -4, 5, -5, 6, -6, 7, -7, 8, -8, 9, -9]


## A-4

In [ ]:
#Answer for A-4

# str.replace()
'''
This function is return  a copy of the string with all occurrences of substring first argument replaced by second 
argument given to the function

text = "We are reviewing python programming topics in ise 291"
new_text = text.replace('ise','ISE')
print(new_text) ==> We are reviewing python programming topics in ISE 291
'''
# str.join()
'''
This function returns a concatanations of the strings in the argument.In other words it returns a new string by joining all the elements 
of an iterable (list, string, tuple), separated by a string separator Argument should be string otherwise it gives a TypeError.

text = ","
new_text = text.join("We are reviewing python programming topics in ise 291")
new_text ==> W,e, ,a,r,e, ,r,e,v,i,e,w,i,n,g, ,p,y,t,h,o,n, ,p,r,o,g,r,a,m,m,i,n,g, ,t,o,p,i,c,s, ,i,n, ,i,s,e, ,2,9,1
'''

# str.split()
'''
This function will break the strings at the specified seperator(by default seperator = ' ') in to list of strings

text = "We are reviewing python programming topics in ise 291"
print(text.split())

['We', 'are', 'reviewing', 'python', 'programming', 'topics', 'in', 'ise', '291']

text = "Apple,Orange,Mango,Grapes"
print(text.split())
['Apple', 'Orange', 'Mango', 'Grapes']
'''

# Which of the above functions transforms a string into a list of strings?
'''
str.split()
'''

# Which of the above functionstransforms a list of strings into one string?
'''
str.join()
'''

## A-5

In [119]:
#Answer for A-5
coded_string = "Rfc `cqr npmep_kq _pc upgrrcl qm rf_r amknsrgle k_afglcq a_l ncpdmpk rfck\n osgaijw?jqm* rfc `cqr npmep_kq _pc upgrrcl qm rf_r fsk_l `cgleq a_l slbcpqr_lb\n rfck ajc_pjw, ? emmb cqq_wgqr _lb _ emmb npmep_kkcp f_tc _ jmr gl amkkml,"
word_list = coded_string.split(' ') # split the wrords by space and geet the word list
print(word_list)

['Rfc', '`cqr', 'npmep_kq', '_pc', 'upgrrcl', 'qm', 'rf_r', 'amknsrgle', 'k_afglcq', 'a_l', 'ncpdmpk', 'rfck\n', 'osgaijw?jqm*', 'rfc', '`cqr', 'npmep_kq', '_pc', 'upgrrcl', 'qm', 'rf_r', 'fsk_l', '`cgleq', 'a_l', 'slbcpqr_lb\n', 'rfck', 'ajc_pjw,', '?', 'emmb', 'cqq_wgqr', '_lb', '_', 'emmb', 'npmep_kkcp', 'f_tc', '_', 'jmr', 'gl', 'amkkml,']


## A-6

In [120]:
#Answer for A-6
new_list = [s.strip() for s in word_list]   # strip() to remove \n character
print(new_list)

['Rfc', '`cqr', 'npmep_kq', '_pc', 'upgrrcl', 'qm', 'rf_r', 'amknsrgle', 'k_afglcq', 'a_l', 'ncpdmpk', 'rfck', 'osgaijw?jqm*', 'rfc', '`cqr', 'npmep_kq', '_pc', 'upgrrcl', 'qm', 'rf_r', 'fsk_l', '`cgleq', 'a_l', 'slbcpqr_lb', 'rfck', 'ajc_pjw,', '?', 'emmb', 'cqq_wgqr', '_lb', '_', 'emmb', 'npmep_kkcp', 'f_tc', '_', 'jmr', 'gl', 'amkkml,']


## A-7

In [121]:
#Answer for A-7
index = 0   
copy_list = []                                                      

for word in new_list:                                           # take each word      
    characters = list(word)                                     # Break the word into list of characters
    characters = [chr(ord(c) + 2) for c in characters]          # get the new computed characters
    copy_list.append(''.join(characters))                       # join the characters and add them into new list

new_list = copy_list                                            # update the new_list

## A-8

In [123]:
#Answer for A-8
new_sentence = ' '.join(new_list)   # join each word by ' ' seperator
print(new_sentence)

The best programs are written so that computing machines can perform them quicklyAlso, the best programs are written so that human beings can understand them clearly. A good essayist and a good programmer have a lot in common.


## A-9

In [124]:
#Answer for A-9
'''
Dictionary is a data type structure that keep value as key and value pairs. Each value has a unique key. Key can be used to get the value
'''
#  What are the possible valid data types for the keys
'''
integer, float, string, or Boolean
'''
# Can a dictionary have mixed data types for the keys (for example, one key is string, another key is integer,etc)? 
'''
yes
'''
numer_dic = {}  # initialize the dictionary
roman = ['X',"XX", "XXX", "XL", "L", "LX", "LXX", "LXXX", "XC", "C"]    # given list
for i in range(0,10):   # Loop 10 times
    numer_dic[i * 10 + 10] = roman[i] # update the key value as 10,20 in each iteration and update relevant idex value from list

print(numer_dic)

{10: 'X', 20: 'XX', 30: 'XXX', 40: 'XL', 50: 'L', 60: 'LX', 70: 'LXX', 80: 'LXXX', 90: 'XC', 100: 'C'}


## A-10

In [126]:
#Answer for A-10
def func(x):
    return (lambda y: y**2 + 2*y + 1 if x >= 0 else y**2 -2*y +1)(x)            # create the lambda function with given x value

list1 = [i if not j else -1 * i for i in range(1,10) for j in range(2)]     # create the list1


results = list(map(func,list1))             # using map function implicitly iterate through the list
print(results)

[4, 4, 9, 9, 16, 16, 25, 25, 36, 36, 49, 49, 64, 64, 81, 81, 100, 100]


# Problem # B

## B-1

In [ ]:
#Answer for B-1

# How to convert an existing list into a numpy array
'''
Using array() method in the numpy package we can turn list into a numpy array
np.array(list)
'''

# How to convert an existing numpy array intoa list
'''
Numpy array has the method call tolist(). This can be used to convert array into a list
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.tolist() ==> [[1, 2, 3], [4, 5, 6]]
'''

## B-2

In [127]:
#Answer for B-2
import numpy as np

np.random.seed(212)                 # Set the random generator seed to be 212

S = np.random.randint(1,21,(10,7))  # Create a random integer numpy nd-array of size 10x7

print(f"S ndim: {S.ndim}")
print(f"S shape: {S.shape}")
print(f"S size: {S.size}") 

S ndim: 2
S shape: (10, 7)
S size: 70


## B-3

In [128]:
#Answer for B-3

# What is the difference between S[:,0] and S[:,[0]]?
'''
S[:,0]   = gives the first column of each row as a one dimensional array
S[:,[0]] = gives the first couumn value as a array in 2d
'''

'\nS[:,0]   = gives the first column of each row as a one dimensional array\nS[:,[0]] = gives the first couumn value as a array in 2d\n'

## B-4

In [129]:
#Answer for B-4
'''
What is the difference between S[0,:] and S[0]
S[0,:] gives the every element of first row
s[0]    Also gives the first row
'''

'\nWhat is the difference between S[0,:] and S[0]\nS[0,:] gives the every element of first row\ns[0]    Also gives the first row\n'

## B-5

In [130]:
#Answer for B-5
arr = np.square(S[:,-2])   # S[:,-2] gives the every rows and -2 gives each of the 2 index value of the rows 
arr.sort()                  # sort the array
print(arr)

[  4  36  49  64 169 169 289 361 400 400]


## B-6

In [131]:
#Answer for B-6
print(S[1:])        

[[16 17 16 14 17 13  2]
 [11 18  4 13  1  6  1]
 [17 17  4  7 18 20 17]
 [ 2  1  6 11 15  8 19]
 [20  3 12 11  8  7  2]
 [16 14  2 11  3  2 10]
 [20 20  1  2 19 20 12]
 [12  9  1 19 17 19  7]
 [ 7  7  3  2  6 17  2]]


## B-7

In [132]:
#Answer for B-7
print(S[::-1])      # Slice the all the rows and reversed to get the reversed columns 

[[ 7  7  3  2  6 17  2]
 [12  9  1 19 17 19  7]
 [20 20  1  2 19 20 12]
 [16 14  2 11  3  2 10]
 [20  3 12 11  8  7  2]
 [ 2  1  6 11 15  8 19]
 [17 17  4  7 18 20 17]
 [11 18  4 13  1  6  1]
 [16 17 16 14 17 13  2]
 [ 3  5 10 15  2 13 20]]


## B-8

In [133]:
#Answer for B-8
print(S[[2,4,5],[3,6,1]])   # Slices and get first 2,4,5 rows and each coresspondig row's 3,6 and 1 column


[13 19  3]


## B-9

In [134]:
#Answer for B-9
mask = S >= 10      # Generate the mask array for given condition
print(S[mask])      # Apply the mask into S and get the values

[10 15 13 20 16 17 16 14 17 13 11 18 13 17 17 18 20 17 11 15 19 20 12 11
 16 14 11 10 20 20 19 20 12 12 19 17 19 17]


## B-10

In [135]:
#Answer for B-10
P = S.copy() # make a copy of S
P[:,3] -= 5  # Using slice and get the reference of the middle coumn of each row and update the value

ones = np.ones((1,7),dtype='int')   # create a row with all ones

P = np.vstack((P[0:5],ones,P[5:]))    # Stack the array verticaly. Fist get the first 5 rows then stack with ones and then get the last 5 rows 
                                    # the P and vstack
print(f"S = {S}")
print("*"*10)
print(f"P = {P}")
 

S = [[ 3  5 10 15  2 13 20]
 [16 17 16 14 17 13  2]
 [11 18  4 13  1  6  1]
 [17 17  4  7 18 20 17]
 [ 2  1  6 11 15  8 19]
 [20  3 12 11  8  7  2]
 [16 14  2 11  3  2 10]
 [20 20  1  2 19 20 12]
 [12  9  1 19 17 19  7]
 [ 7  7  3  2  6 17  2]]
**********
P = [[ 3  5 10 10  2 13 20]
 [16 17 16  9 17 13  2]
 [11 18  4  8  1  6  1]
 [17 17  4  2 18 20 17]
 [ 2  1  6  6 15  8 19]
 [ 1  1  1  1  1  1  1]
 [20  3 12  6  8  7  2]
 [16 14  2  6  3  2 10]
 [20 20  1 -3 19 20 12]
 [12  9  1 14 17 19  7]
 [ 7  7  3 -3  6 17  2]]
