<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Group-Number,-Names-&amp;-IDs" data-toc-modified-id="Group-Number,-Names-&amp;-IDs-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Group Number, Names &amp; IDs</a></span></li><li><span><a href="#Problem-#A" data-toc-modified-id="Problem-#A-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Problem #A</a></span></li><li><span><a href="#Problem-#B" data-toc-modified-id="Problem-#B-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Problem #B</a></span></li></ul></div>

# Group Number, Names & ID


# Problem #A

In [ ]:
#A-1
l = list(range(-1, -11, -1))  # [-1, -2, ...., -10]
l2 = [i/2 if i%2 ==0 else i for i in l] # Divide every even by 2
print(l2)

In [ ]:
#A-2
l = [i if j == 0 else -i for i in range(1,10) for j in range(2)] # Add alternative positive/negative values
print(l)

In [ ]:
#A-3

st = '''Vjg dguv rtqitcou ctg ytkvvgp uq vjcv eqorwvkpi ocejkpgu ecp rgthqto vjgo
swkemn{0 Cnuq. vjg dguv rtqitcou ctg ytkvvgp uq vjcv jwocp dgkpiu ecp wpfgtuvcpf
vjgo engctn{0 C iqqf guuc{kuv cpf c iqqf rtqitcoogt jcxg c nqv kp eqooqp0'''

l3 = st.split() # split the sentence into a list of words
print(l3)

In [ ]:
#A-4

l4 = [i.strip() for i in l3] # to remove newline characters (if any)
print(l3)

In [ ]:
#A-5
    # Breakdown the word into list of letters.
    # Convert each of the above letters into integer, using ord() function.
    # Update the integer values by -2 for all the above integers.
    # Convert each updated integer value into letter, using chr() function.
    # Join the updated letters in the order to create new word.
l5 = list(map(lambda word: "".join([chr(ord(cr)-2) for cr in list(word) if cr != " "]), l4))
print(l5)

In [ ]:
#A-6

s6 = " ".join(l5) # to Join the list of new words into one string of words
print(s6)

In [ ]:
#A-7
    # Ask the user to enter a number from the following choices: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
    # Returns the roman numerals and the word form for the entered number.
    
print({"10" : "X Ten", "20" : "XX Twenty", "30" : "XXX Thirty", "40" : "XL Forty", "50" : "L Fifty", "60" : "LX Sixty", "70" : "LXX Seventy",
    "80" : "LXXX Eighty", "90" : "XC Ninety", "100" : "C One Hundred"}.get(input("Enter a number from the following choices: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100: ")))

# Problem #B

In [ ]:
#B-1 
import numpy as np
np.random.seed(211)
S = np.random.randint(0,10,(8,9)) #to create a random integer numpy nd-array of size 8x9
print(S)

[[6 6 6 4 0 9 7 9 2]
 [3 9 7 3 9 0 1 3 2]
 [2 3 0 7 8 6 6 9 0]
 [4 7 7 8 7 3 3 1 0]
 [1 2 5 8 9 3 7 2 3]
 [0 7 1 6 1 5 6 3 6]
 [7 8 5 5 1 9 2 2 5]
 [5 1 7 4 2 4 9 8 4]]


In [ ]:
#B-2
    # to print the dimensions, shape and size of S
print(f'Number of dimensions: {S.ndim}')
print(f'Size: {S.size}')
print(f'Shape: {S.shape[0]}x{S.shape[1]}')

In [ ]:
#B-3
print(S[-2] ** 2) # Print squares of all the elements of the last but one row (index -2 ) of S

In [ ]:
#B-4
print(S[:,-2]/10) # Print 1/10 th of all the elements of the second column from the end (index -2 ) of S

In [ ]:
#B-5
print(S[1::2]) # Print alternate rows starting from row indexed 1, and all the columns of S

In [ ]:
#B-6
print(S[:,2::2]) # Print all the rows, and alternate columns starting from column indexed 2 of S.

In [ ]:
#B-7
print(S[::-1]) # Print S with all rows reversed

In [ ]:
#B-8
print(S[:,::-1]) # Print S with all columns reversed.

In [ ]:
#B-9
    # Print a slice of S containing rows indexed [2,4,5] in order, and columns indexed [3,6,1] in order.
print(S[[2,4,5]][:,[3,6,1]]) 

In [ ]:
#B-10
    # Create a copy of S, say P. Subtract −9 from all the middle column elements of P.
    # Insert a newrow of all ones in the middle P, such that the new dimesions of P become 9x9.
    # Print both S and P.
P = S.copy()
P[:, S.shape[1]//2] -= 9
P = np.vstack((P[:P.shape[0]//2], np.ones(P.shape[1], dtype = "int"), P[P.shape[0]//2:]))
print(S, S.shape)
print(P, P.shape)

# Problem #D

In [ ]:
np.random.seed(211)
D = np.random.randint(10,90,(5,8))
print(D)

[[16 80 14 52 85 26 86 40]
 [24 57 12 29 35 39 25 33]
 [24 29 83 26 52 27 40 77]
 [28 13 82 53 39 53 25 80]
 [56 37 87 54 43 10 59 47]]


In [ ]:
D -= 5
print(D)

[[11 75  9 47 80 21 81 35]
 [19 52  7 24 30 34 20 28]
 [19 24 78 21 47 22 35 72]
 [23  8 77 48 34 48 20 75]
 [51 32 82 49 38  5 54 42]]


In [ ]:
D[2] = D[2]-5
print(D)

[[11 75  9 47 80 21 81 35]
 [19 52  7 24 30 34 20 28]
 [14 19 73 16 42 17 30 67]
 [23  8 77 48 34 48 20 75]
 [51 32 82 49 38  5 54 42]]


In [ ]:
D[:,4] = D[:,4]-5
print(D)

[[11 75  9 47 75 21 81 35]
 [19 52  7 24 25 34 20 28]
 [14 19 73 16 37 17 30 67]
 [23  8 77 48 29 48 20 75]
 [51 32 82 49 33  5 54 42]]


In [ ]:
D[1:3] = D[1:3]/10
print(D)

[[11 75  9 47 75 21 81 35]
 [ 1  5  0  2  2  3  2  2]
 [ 1  1  7  1  3  1  3  6]
 [23  8 77 48 29 48 20 75]
 [51 32 82 49 33  5 54 42]]


In [ ]:
D1 = D.copy()
D1[(D1 < 50)] = 0
D1[(D1 >= 50)] = 100
print(D)
print(D1)

[[11 75  9 47 75 21 81 35]
 [ 1  5  0  2  2  3  2  2]
 [ 1  1  7  1  3  1  3  6]
 [23  8 77 48 29 48 20 75]
 [51 32 82 49 33  5 54 42]]
[[  0 100   0   0 100   0 100   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0 100   0   0   0   0 100]
 [100   0 100   0   0   0 100   0]]


In [ ]:
D2, D3= np.split(D1, 2)
print(D2, np.shape(D2))

print(D3, np.shape(D3))

ValueError: array split does not result in an equal division

In [ ]:
array1 =np.array([1,2,3,4])
print((lambda x: x * 3 )(array1))


[ 3  6  9 12]
