In [4]:
list1 = [i for i in range(1,10)]
print(list1)
list2 = [(i,i**2) for i in list1]
print(list2)
list3 = [i for tup in list2 for i in tup ]
print(list3)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[(1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81)]
[1, 1, 2, 4, 3, 9, 4, 16, 5, 25, 6, 36, 7, 49, 8, 64, 9, 81]


In [9]:
text = ['Excellent', 'Very Good', 'Good', 'Poor', 'Very Poor']
val = [5,4,3,2,1]

dict1 = {k:i for k,i in zip(text,val)}
print(dict1)

list3 = list(map(lambda x : dict1[x],['Good', 'Excellent', 'Very Good', 'Very Poor', 'Excellent', 'Poor', 'Very Poor', 'Poor', 'Poor', 'Good']))
list3

{'Excellent': 5, 'Very Good': 4, 'Good': 3, 'Poor': 2, 'Very Poor': 1}


[3, 5, 4, 1, 5, 2, 1, 2, 2, 3]

In [17]:
import numpy as np
np.random.seed(1)
X = np.random.randint(10,31,(6,5))
print(X)
print(X[:,::2])
print(X[1::2,:])
print(X[X % 5 == 0])

[[15 21 22 18 19]
 [21 15 25 10 26]
 [11 22 17 23 16]
 [28 30 15 28 30]
 [21 20 24 28 14]
 [19 27 10 23 19]]
[[15 22 19]
 [21 25 26]
 [11 17 16]
 [28 15 30]
 [21 24 14]
 [19 10 19]]
[[21 15 25 10 26]
 [28 30 15 28 30]
 [19 27 10 23 19]]
[15 15 25 10 30 15 30 20 10]


In [22]:
text = "the old lady pulled her spectacles down and looked over them about the room; then she put them up and looked out under them. she seldom or never looked THROUGH them for so small a thing as a boy; they were her state pair, the pride of her heart, and were built for style, not service she could have seen THROUGH a pair of stove-lids just as well. she looked perplexed for a moment, and then said, not fiercely, but still loud enough for the furniture to hear."

string1 = text.replace(",","").replace(";","").replace("THROUGH","THROUGH".lower())
print(string1)

list_of_words = string1.split(" ")
print("|".join(list_of_words))

the old lady pulled her spectacles down and looked over them about the room then she put them up and looked out under them. she seldom or never looked through them for so small a thing as a boy they were her state pair the pride of her heart and were built for style not service she could have seen through a pair of stove-lids just as well. she looked perplexed for a moment and then said not fiercely but still loud enough for the furniture to hear.
the|old|lady|pulled|her|spectacles|down|and|looked|over|them|about|the|room|then|she|put|them|up|and|looked|out|under|them.|she|seldom|or|never|looked|through|them|for|so|small|a|thing|as|a|boy|they|were|her|state|pair|the|pride|of|her|heart|and|were|built|for|style|not|service|she|could|have|seen|through|a|pair|of|stove-lids|just|as|well.|she|looked|perplexed|for|a|moment|and|then|said|not|fiercely|but|still|loud|enough|for|the|furniture|to|hear.


In [24]:
## This is the above data in python list format. Execute this cell in-order to use the following lists/data
City_1=[215, 88, 185, 226, 195, 176, 241 ,205, 224, 183, 192, 391, 116, 225, 168, 188, 204 ,191 ,213 ,243]
City_2=[201, 197, 234, 196, 236, 463, 433, 178, 230, 247, 103, 214, 333, 257, 246, 297, 171, 198, 288, 263]
City_3=[371, 215, 247, 200, 76, 249, 197, 236, 177, 126, 210, 263, 111, 213, 195, 236, 270, 206, 193, 241]
Total_Death_Cases=[14, 7, 16, 12, 6, 21, 11, 7, 17, 10, 5, 20, 11, 21, 7, 7, 11, 9, 9, 8]
Main_Cause= ['Over-Speeding','Rash Driving','Over-Speeding','Violation of Rules','Over-Speeding','Rash Driving',
'Over-Speeding', 'Violation of Rules','Rash Driving','Over-Speeding','Rash Driving','Over-Speeding','Violation of Rules',
'Over-Speeding','Over-Speeding','Rash Driving','Over-Speeding','Violation of Rules','Rash Driving','Over-Speeding']

In [27]:
# Null hypothesis = Total death cases follow normal distribution
from scipy.stats import shapiro
_,pval = shapiro(Total_Death_Cases)
if pval <0.05:
    print("We reject the null hypothesis")
else:
    print("We failed to reject the null hypothesis")

We reject the null hypothesis


In [ ]:
import matplotlib.pyplot as plt

plt.figure()
plt.boxplot('')